[server]
ip = "127.0.0.1"
port = 8080

[redis]
ip = "127.0.0.1"
db = 11

[source]
api_url = "http://localhost:3000/api/v1/rating_summaries.json"
api_user = "your_user_here"
api_password = "your_pass_here"
